name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'
      - name: Install dependencies
        run: go get .
      - name: Build release
        run: go build
      - name: Pack release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
            mkdir bango-${{github.ref_name}}
            strip bango
            cp -a bango README.md LICENSE bango.ini actions bango-${{github.ref_name}}/
            tar czpf bango-${{github.ref_name}}.tar.gz bango-${{github.ref_name}}
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bango-${{github.ref_name}}.tar.gz
