name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go get .
      - name: Build release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
            go build
            mkdir bango-${{github.ref_name}}
            strip bango
            cp bango README.md LICENSE bango-${{github.ref_name}}/
            tar czpf bango-${{github.ref_name}}.tar.gz bango-${{github.ref_name}}
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bango-${{github.ref_name}}.tar.gz
